name: elk

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
    container_name: elasticsearch
    restart: always
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    networks:
      - elastic-net
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
      cluster.name: dev-cluster
      node.name: dev-node
      ELASTIC_PASSWORD: $ELASTIC_PASSWORD
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 9200 || exit 1" ]
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 20s
  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.0
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - elastic-net
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:5601 > /dev/null || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  elastic-data: {}

networks:
  elastic-net: {}
