name: elk

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
    container_name: elasticsearch
    restart: always
    networks:
      - elastic-net
    ports:
      - 9200:9200
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.0
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - elastic-net
    depends_on:
      - elasticsearch

networks:
  elastic-net: {}
